version: '3.9'

services:
  dx-web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - 5000:5000
    restart: always
    env_file: .env
    environment:
      - PORT=5000
      - VITE_BASE_URL=http://web:5000
